name: Fix PR

on:
  workflow_dispatch:
    inputs:
      base_branch_name:
        required: true
        type: string
      aider_message:
        required: true
        type: string
      base_pull_request_number:
        required: true
        type: number

jobs:
  fix-pr:
    runs-on: ubuntu-latest
    env:
      AIDER_YES_ALWAYS: true
      AIDER_AUTO_COMMITS: true
      AIDER_CACHE_PROMPTS: true
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      AIDER_MESSAGE: ${{inputs.aider_message}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Aider
        run: curl -LsSf https://aider.chat/install.sh | sh
      - name: Run Aider
        run: echo "aider_output=$(aider)" >> $GITHUB_OUTPUT
        id: run_aider
      - name: Extract Commit Message
        id: extract_commit
        run: |
          AIDER_OUTPUT="${{ steps.run_aider.outputs.aider_output }}"
          COMMIT_MESSAGE=$(echo "$AIDER_OUTPUT" | grep -o "Commit [a-f0-9]* .*" | sed 's/Commit [a-f0-9]* //')
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{inputs.base_branch_name}}
          branch: "fix-pr-${{inputs.base_pull_request_number}}"
          author: Fix PR Bot
          committer: Fix PR Bot
          title: ${{steps.extract_commit.outputs.commit_message}}
          body: |
            Address review comments for PR #${{inputs.base_pull_request_number}}
            Auto-generated by Fix PR
