name: Fix PR

on:
  workflow_dispatch:
    inputs:
      comment:
        required: true
        type: string

jobs:
  fix-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Echo comment
        run: echo ${{ inputs.comment }}
